TKusy\Hl7FhirR4\ProductShelfLifeType:
    properties:
        identifier:
            expose: true
            access_type: public_method
            serialized_name: identifier
            xml_element:
                cdata: false
                namespace: 'http://hl7.org/fhir'
            accessor:
                getter: getIdentifier
                setter: setIdentifier
            type: TKusy\Hl7FhirR4\IdentifierType
        type:
            expose: true
            access_type: public_method
            serialized_name: type
            xml_element:
                cdata: false
                namespace: 'http://hl7.org/fhir'
            accessor:
                getter: getType
                setter: setType
            type: TKusy\Hl7FhirR4\CodeableConceptType
        period:
            expose: true
            access_type: public_method
            serialized_name: period
            xml_element:
                cdata: false
                namespace: 'http://hl7.org/fhir'
            accessor:
                getter: getPeriod
                setter: setPeriod
            type: TKusy\Hl7FhirR4\QuantityType
        specialPrecautionsForStorage:
            expose: true
            access_type: public_method
            serialized_name: specialPrecautionsForStorage
            xml_element:
                cdata: false
                namespace: 'http://hl7.org/fhir'
            accessor:
                getter: getSpecialPrecautionsForStorage
                setter: setSpecialPrecautionsForStorage
            xml_list:
                inline: true
                entry_name: specialPrecautionsForStorage
                namespace: 'http://hl7.org/fhir'
            type: array<TKusy\Hl7FhirR4\CodeableConceptType>
